version: "3.3"
services:
  bitcoin-core:
    ports:
      - "8333:8333"
    container_name: bitcoin-core
    image: ruimarinho/bitcoin-core
    restart: always
    volumes:
      - ./bitcoin:/home/bitcoin/.bitcoin
    networks:
      bitcoin:
        ipv4_address: 172.18.0.2
    command:
      - "-prune=${PRUNE:-550}"
      - "-rpcbind=127.0.0.1"
      - "-rpcallowip=127.0.0.1"
      - "-rpcbind=172.18.0.2"
      - "-rpcallowip=172.18.0.0/16"
      - "-rpcauth=${RPCAUTH:?use rpcauth.py to create a password and set the RPCPASS in .env}"
      - "-zmqpubrawblock=tcp://172.18.0.2:28332"
      - "-zmqpubrawtx=tcp://172.18.0.2:28333"
  lnd-1:
    ports:
      - "9735:9735"
      - "10009:10009"
    image: joshuanapoli/lnd:v0.14.1-beta
    container_name: lnd-1
    depends_on:
      - bitcoin-core
    restart: always
    volumes:
      - ./lnd-1:/root/.lnd
    networks:
      bitcoin:
        ipv4_address: 172.18.1.1
    command:
      - "--bitcoin.active"
      - "--bitcoin.mainnet"
      - "--bitcoin.node=bitcoind"
      - "--bitcoind.rpcuser=${RPCUSER:-lnd}"
      - "--bitcoind.rpcpass=${RPCPASS:?use rpcauth.py to create a password and set the RPCPASS in .env}"
      - "--bitcoind.rpchost=bitcoin-core"
      - "--bitcoind.zmqpubrawblock=tcp://bitcoin-core:28332"
      - "--bitcoind.zmqpubrawtx=tcp://bitcoin-core:28333"
      - "--externalip=${EXTERNALIP}:9735"
      - "--alias=${ALIAS-1}"
      - "--rpclisten=0.0.0.0:10009"
      - "--tlsextradomain=${TLSEXTRADOMAIN}"
  lnd-2:
    ports:
      - "9737:9735"
      - "10011:10009"
    image: joshuanapoli/lnd:v0.14.1-beta
    container_name: lnd-2
    depends_on:
      - bitcoin-core
    restart: always
    volumes:
      - ./lnd-2:/root/.lnd
    networks:
      bitcoin:
        ipv4_address: 172.18.1.2
    command:
      - "--bitcoin.active"
      - "--bitcoin.mainnet"
      - "--bitcoin.node=bitcoind"
      - "--bitcoind.rpcuser=${RPCUSER:-lnd}"
      - "--bitcoind.rpcpass=${RPCPASS:?use rpcauth.py to create a password and set the RPCPASS in .env}"
      - "--bitcoind.rpchost=bitcoin-core"
      - "--bitcoind.zmqpubrawblock=tcp://bitcoin-core:28332"
      - "--bitcoind.zmqpubrawtx=tcp://bitcoin-core:28333"
      - "--externalip=${EXTERNALIP}:9737"
      - "--alias=${ALIAS-2}"
      - "--rpclisten=0.0.0.0:10009"
      - "--tlsextradomain=${TLSEXTRADOMAIN}"
  lnd-3:
    ports:
      - "9739:9735"
      - "10013:10009"
    image: joshuanapoli/lnd:v0.14.1-beta
    container_name: lnd-3
    depends_on:
      - bitcoin-core
    restart: always
    volumes:
      - ./lnd-3:/root/.lnd
    networks:
      bitcoin:
        ipv4_address: 172.18.1.3
    command:
      - "--bitcoin.active"
      - "--bitcoin.mainnet"
      - "--bitcoin.node=bitcoind"
      - "--bitcoind.rpcuser=${RPCUSER:-lnd}"
      - "--bitcoind.rpcpass=${RPCPASS:?use rpcauth.py to create a password and set the RPCPASS in .env}"
      - "--bitcoind.rpchost=bitcoin-core"
      - "--bitcoind.zmqpubrawblock=tcp://bitcoin-core:28332"
      - "--bitcoind.zmqpubrawtx=tcp://bitcoin-core:28333"
      - "--externalip=${EXTERNALIP}:9739"
      - "--alias=${ALIAS-3}"
      - "--rpclisten=0.0.0.0:10009"
      - "--tlsextradomain=${TLSEXTRADOMAIN}"

networks:
  bitcoin:
    ipam:
      config:
        - subnet: 172.18.0.0/16
