version: "3.3"
services:
  lnd:
    ports:
      - "8080:8080"
      - "9735:9735"
      - "10009:10009"
    image: joshuanapoli/lnd:v0.15.0-beta # Same as https://hub.docker.com/r/lightninglabs/lnd plus Raspberry Pi support
    container_name: lnd
    restart: always
    volumes:
      - ./lnd:/root/.lnd
      - ./st-sync:/var/syncthing
    networks:
      bitcoin:
        ipv4_address: 172.18.1.1
    command:
      - "--accept-amp"
      - "--alias=${ALIAS}"
      - "--backupfilepath=/var/syncthing/Sync/channel.backup"
      - "--bitcoin.active"
      - "--bitcoin.mainnet"
      - "--bitcoin.node=bitcoind"
      - "--bitcoind.rpchost=bitcoin-core"
      - "--bitcoind.rpcpass=${RPCPASS:?use rpcauth.py to create a password and set the RPCPASS in .env}"
      - "--bitcoind.rpcuser=${RPCUSER:-lnd}"
      - "--bitcoind.zmqpubrawblock=tcp://bitcoin-core:28332"
      - "--bitcoind.zmqpubrawtx=tcp://bitcoin-core:28333"
      - "--externalip=${EXTERNALIP}"
      - "--restlisten=0.0.0.0:8080"
      - "--rpclisten=0.0.0.0:10009"
      - "--tlsextradomain=${HOST}"
      - "--tlsextraip=172.18.1.1"

# We can run lightning-terminal, but it's not needed...
#  lightning-terminal:
#    ports:
#      - "80:80"
#      - "8443:8443"
#    image: joshuanapoli/lightning-terminal:v0.6.1-alpha
#    container_name: lightning-terminal
#    depends_on:
#      - lnd
#    restart: always
#    volumes:
#      - ./lightning-terminal:/root/.lightning-terminal
#      - ./lnd:/root/.lnd
#    networks:
#      bitcoin:
#        ipv4_address: 172.18.2.1
#    command:
#      - "--remote.lnd.rpcserver=172.18.1.1:10009"
#      - "--uipassword=${LITDPASS:?create a password and set the LITDPASS in .env}"
#      - "--httpslisten=0.0.0.0:8443"
#      - "--letsencrypt"
#      - "--letsencrypthost=${HOST}"

  rtl:
    container_name: rtl
    image: shahanafarooqui/rtl:0.12.3
    restart: always
    depends_on:
      - lnd
    volumes:
      - ./lnd:/lnd:ro
      - ./rtl:/rtl
      - ./st-sync:/var/syncthing
    ports:
      - "3000:3000"
    networks:
      bitcoin:
        ipv4_address: 172.18.3.1
    environment:
      PORT: 3000
      MACAROON_PATH: /lnd/data/chain/bitcoin/mainnet
      LN_SERVER_URL: https://172.18.1.1:8080
      LN_IMPLEMENTATION: LND
      RTL_SSO: 0
      RTL_COOKIE_PATH: ''
      RTL_CONFIG_PATH: /rtl
      CHANNEL_BACKUP_PATH: /var/syncthing/Sync

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: lnd-${ALIAS}
    environment:
      - PUID=0 # dangerously run as root because lnd runs as root (need to change the lnd docker to run as non-root)
      - PGID=0
    volumes:
      - ./st-sync:/var/syncthing
    restart: always
    network_mode: host # host network mode required for local device discovery

networks:
  bitcoin:
    ipam:
      config:
        - subnet: 172.18.0.0/16
